// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protometry.proto

package protometry

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VectorN struct {
	Dimensions           []float64 `protobuf:"fixed64,1,rep,packed,name=dimensions,proto3" json:"dimensions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *VectorN) Reset()         { *m = VectorN{} }
func (m *VectorN) String() string { return proto.CompactTextString(m) }
func (*VectorN) ProtoMessage()    {}
func (*VectorN) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f5d407279f65988, []int{0}
}

func (m *VectorN) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VectorN.Unmarshal(m, b)
}
func (m *VectorN) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VectorN.Marshal(b, m, deterministic)
}
func (m *VectorN) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VectorN.Merge(m, src)
}
func (m *VectorN) XXX_Size() int {
	return xxx_messageInfo_VectorN.Size(m)
}
func (m *VectorN) XXX_DiscardUnknown() {
	xxx_messageInfo_VectorN.DiscardUnknown(m)
}

var xxx_messageInfo_VectorN proto.InternalMessageInfo

func (m *VectorN) GetDimensions() []float64 {
	if m != nil {
		return m.Dimensions
	}
	return nil
}

type QuaternionN struct {
	Value                *VectorN `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuaternionN) Reset()         { *m = QuaternionN{} }
func (m *QuaternionN) String() string { return proto.CompactTextString(m) }
func (*QuaternionN) ProtoMessage()    {}
func (*QuaternionN) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f5d407279f65988, []int{1}
}

func (m *QuaternionN) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuaternionN.Unmarshal(m, b)
}
func (m *QuaternionN) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuaternionN.Marshal(b, m, deterministic)
}
func (m *QuaternionN) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuaternionN.Merge(m, src)
}
func (m *QuaternionN) XXX_Size() int {
	return xxx_messageInfo_QuaternionN.Size(m)
}
func (m *QuaternionN) XXX_DiscardUnknown() {
	xxx_messageInfo_QuaternionN.DiscardUnknown(m)
}

var xxx_messageInfo_QuaternionN proto.InternalMessageInfo

func (m *QuaternionN) GetValue() *VectorN {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*VectorN)(nil), "protometry.VectorN")
	proto.RegisterType((*QuaternionN)(nil), "protometry.QuaternionN")
}

func init() { proto.RegisterFile("protometry.proto", fileDescriptor_7f5d407279f65988) }

var fileDescriptor_7f5d407279f65988 = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xcf, 0x4d, 0x2d, 0x29, 0xaa, 0xd4, 0x03, 0x33, 0x85, 0xb8, 0x10, 0x22, 0x4a, 0x9a, 0x5c,
	0xec, 0x61, 0xa9, 0xc9, 0x25, 0xf9, 0x45, 0x7e, 0x42, 0x72, 0x5c, 0x5c, 0x29, 0x99, 0xb9, 0xa9,
	0x79, 0xc5, 0x99, 0xf9, 0x79, 0xc5, 0x12, 0x8c, 0x0a, 0xcc, 0x1a, 0x8c, 0x41, 0x48, 0x22, 0x4a,
	0x16, 0x5c, 0xdc, 0x81, 0xa5, 0x89, 0x25, 0xa9, 0x45, 0x79, 0x99, 0xf9, 0x79, 0x7e, 0x42, 0x9a,
	0x5c, 0xac, 0x65, 0x89, 0x39, 0xa5, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0xc2, 0x7a,
	0x48, 0xf6, 0x40, 0x8d, 0x0c, 0x82, 0xa8, 0x70, 0xd2, 0xe6, 0xe2, 0x4b, 0xce, 0xcf, 0x45, 0x52,
	0xe0, 0xc4, 0x15, 0x00, 0x67, 0x07, 0x30, 0xae, 0x62, 0x42, 0xe2, 0x26, 0xb1, 0x81, 0x95, 0x19,
	0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x1f, 0x93, 0xc8, 0x58, 0xb8, 0x00, 0x00, 0x00,
}
