// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vectorn.proto

package protometry

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VectorN struct {
	Dimensions           []float64 `protobuf:"fixed64,1,rep,packed,name=dimensions,proto3" json:"dimensions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *VectorN) Reset()         { *m = VectorN{} }
func (m *VectorN) String() string { return proto.CompactTextString(m) }
func (*VectorN) ProtoMessage()    {}
func (*VectorN) Descriptor() ([]byte, []int) {
	return fileDescriptor_c38cd87c3fa235d4, []int{0}
}

func (m *VectorN) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VectorN.Unmarshal(m, b)
}
func (m *VectorN) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VectorN.Marshal(b, m, deterministic)
}
func (m *VectorN) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VectorN.Merge(m, src)
}
func (m *VectorN) XXX_Size() int {
	return xxx_messageInfo_VectorN.Size(m)
}
func (m *VectorN) XXX_DiscardUnknown() {
	xxx_messageInfo_VectorN.DiscardUnknown(m)
}

var xxx_messageInfo_VectorN proto.InternalMessageInfo

func (m *VectorN) GetDimensions() []float64 {
	if m != nil {
		return m.Dimensions
	}
	return nil
}

func init() {
	proto.RegisterType((*VectorN)(nil), "protometry.VectorN")
}

func init() { proto.RegisterFile("vectorn.proto", fileDescriptor_c38cd87c3fa235d4) }

var fileDescriptor_c38cd87c3fa235d4 = []byte{
	// 104 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4b, 0x4d, 0x2e,
	0xc9, 0x2f, 0xca, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x02, 0x53, 0xb9, 0xa9, 0x25,
	0x45, 0x95, 0x4a, 0x9a, 0x5c, 0xec, 0x61, 0x60, 0x49, 0x3f, 0x21, 0x39, 0x2e, 0xae, 0x94, 0xcc,
	0xdc, 0xd4, 0xbc, 0xe2, 0xcc, 0xfc, 0xbc, 0x62, 0x09, 0x46, 0x05, 0x66, 0x0d, 0xc6, 0x20, 0x24,
	0x11, 0x27, 0x6d, 0x2e, 0xbe, 0xe4, 0xfc, 0x5c, 0x3d, 0x84, 0x66, 0x27, 0xae, 0x00, 0x38, 0x3b,
	0x80, 0x71, 0x15, 0x13, 0x12, 0x37, 0x89, 0x0d, 0xac, 0xcc, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff,
	0xaa, 0xa9, 0xf3, 0x78, 0x7b, 0x00, 0x00, 0x00,
}
